config/routes.rb
Rails.application.routes.draw do
  resources :sign_ups
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :writers
  # resources :users

   root 'welcome#index'

   resources :users
    resources :articles do
      resources :comments
    # get 'my_method', on: :member
     end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sign_up.rb
class SignUp < ApplicationRecord
end

app/controllers/sign_ups_controller.rb
class SignUpsController < ApplicationController
  before_action :set_sign_up, only: [:show, :edit, :update, :destroy]

  # GET /sign_ups
  # GET /sign_ups.json
  def index
    @sign_ups = SignUp.all
  end

  # GET /sign_ups/1
  # GET /sign_ups/1.json
  def show
  end

  # GET /sign_ups/new
  def new
    @sign_up = SignUp.new
  end

  # GET /sign_ups/1/edit
  def edit
  end

  # POST /sign_ups
  # POST /sign_ups.json
  def create
    @sign_up = SignUp.new(sign_up_params)

    respond_to do |format|
      if @sign_up.save
        log_in @sign_up
        flash[:success] = "Welcome to the Sample App!"

        format.html { redirect_to @sign_up, notice: 'Sign up was successfully created.' }
        format.json { render :show, status: :created, location: @sign_up }
      else
        format.html { render :new }
        format.json { render json: @sign_up.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sign_ups/1
  # PATCH/PUT /sign_ups/1.json
  def update
    respond_to do |format|
      if @sign_up.update(sign_up_params)
        format.html { redirect_to @sign_up, notice: 'Sign up was successfully updated.' }
        format.json { render :show, status: :ok, location: @sign_up }
      else
        format.html { render :edit }
        format.json { render json: @sign_up.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sign_ups/1
  # DELETE /sign_ups/1.json
  def destroy
    @sign_up.destroy
    respond_to do |format|
      format.html { redirect_to sign_ups_url, notice: 'Sign up was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sign_up
      @sign_up = SignUp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sign_up_params
      params.require(:sign_up).permit(:name, :email, :password, :address)
    end
end

app/helpers/sign_ups_helper.rb
module SignUpsHelper
end

app/views/sign_ups/_form.html.erb
<%= form_with(model: sign_up, local: true) do |form| %>
  <% if sign_up.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sign_up.errors.count, "error") %> prohibited this sign_up from being saved:</h2>

      <ul>
      <% sign_up.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :sign_up_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :sign_up_email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :sign_up_password %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :sign_up_address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sign_ups/edit.html.erb
<h1>Editing Sign Up</h1>

<%= render 'form', sign_up: @sign_up %>

<%= link_to 'Show', @sign_up %> |
<%= link_to 'Back', sign_ups_path %>

app/views/sign_ups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sign Ups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sign_ups.each do |sign_up| %>
      <tr>
        <td><%= sign_up.name %></td>
        <td><%= sign_up.email %></td>
        <td><%= sign_up.password %></td>
        <td><%= sign_up.address %></td>
        <td><%= link_to 'Show', sign_up %></td>
        <td><%= link_to 'Edit', edit_sign_up_path(sign_up) %></td>
        <td><%= link_to 'Destroy', sign_up, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sign Up', new_sign_up_path %>

app/views/sign_ups/new.html.erb
<h1>New Sign Up</h1>

<%= render 'form', sign_up: @sign_up %>

<%= link_to 'Back', sign_ups_path %>

app/views/sign_ups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sign_up.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @sign_up.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @sign_up.password %>
</p>

<p>
  <strong>Address:</strong>
  <%= @sign_up.address %>
</p>

<%= link_to 'Edit', edit_sign_up_path(@sign_up) %> |
<%= link_to 'Back', sign_ups_path %>